import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar"
import Footer from "@/components/layout/Footer";
import MERRIWEATHER_SANS from "@/app/font"
import "../../styles/globals.css";

export const metadata: Metadata = {
    title: "Demirel İnşaat",
    description: "Generated by create next app",
};

export default function PublicLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={MERRIWEATHER_SANS.className}>
        <body>
        <Navbar/>
        <main className="min-h-screen">{children}</main>
        <Footer/>
        </body>
        </html>
    );
}
