import "../styles/globals.css"; 
import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar"
import MERRIWEATHER_SANS from "@/app/font"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={MERRIWEATHER_SANS.className}>
      <body>
        <Navbar/>
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
